"""empty message

Revision ID: fbe2e8199dd7
Revises: 
Create Date: 2019-09-16 14:56:24.073853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbe2e8199dd7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_time', sa.DATE(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('province_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_time', sa.DATE(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('province_info')
    op.drop_table('city_info')
    # ### end Alembic commands ###
